spring:
  config:
    activate:
      on-profile: dev
      
#MongoDB properties
  data:
    mongodb:
      uri: mongodb://user:password@localhost/car-service-nosql-db
      auto-index-creation: true

#Eureka properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
