spring:
  config:
    activate:
      on-profile: dev

#Datasource properties
  datasource:
    url: jdbc:mysql://localhost:3306/car-service-db
    username: user
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

#r2dbc properties
  r2dbc:
    url: r2dbc:mysql://localhost:3306/car-service-db
    username: user
    password: 123456

#Flyway properties
  flyway:
    url: jdbc:mysql://localhost:3306/car-service-db
    user: user
    password: 123456
    locations: classpath:db/mysql/migrations

    #Eureka properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
