spring:
  config:
    activate:
      on-profile: docker
      
#MongoDB properties
  data:
    mongodb:
      uri: mongodb://user:password@car-service-mongodb/car-service-nosql-db
      auto-index-creation: true
      
#Eureka properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://car-service-eureka-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
