spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      uri: http://localhost:8888
      enabled: true
      
#Eureka properties
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
