spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      uri: http://car-service-config-service:8888
      enabled: true
      
#Datasource properties
  datasource:
    url: jdbc:mysql://car-service-mysql-db:3306/car-service-db
    username: user
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

#r2dbc properties
  r2dbc:
    url: r2dbc:mysql://car-service-mysql-db:3306/car-service-db
    username: user
    password: 123456

#Flyway properties
  flyway:
    url: jdbc:mysql://car-service-mysql-db:3306/car-service-db
    user: user
    password: 123456
    locations: classpath:db/mysql/migrations

    #Eureka properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://car-service-eureka-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
