spring:
  config:
    activate:
      on-profile: dev
      
#Eureka properties
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


---
spring:
  config:
    activate:
      on-profile: docker
      
#Eureka properties
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

